[package]
name = "fpm"
version = "0.1.10"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
]
edition = "2018"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/FifthTry/fpm"
homepage = "https://fpm.dev"
build = "build.rs"

[features]
controller = []
remote = []
local = []


[dependencies]
edit = "0.1.4"
async-recursion = "0.3.2"
camino = "1.0.5"
clap = "2.33.3"
diffy = "0.2.1"
ftd = { git = "https://github.com/FifthTry/ftd", rev = "966e7c9" }
# ftd = { path = "../ftd" }
futures = "0.3"
home = "0.5.3"
ignore = "0.4.18"
indoc = "1.0"
regex = "1.5.5"
#reqwest = { version = "0.11.10", features = ["blocking"] }
reqwest = { version = "0.9.18"}
rusqlite = { version = "0.26.3", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1"
thiserror = "1.0"
tokio = { version = "1.14.0", features = ["full"] }
url = "2.2.2"
zip = "0.5"
colorize = "0.1.0"
chrono = "0.4.19"
fluent = "0.16"
lazy_static = "1"
realm-lang = "0.1.0"
antidote = "1"
intl-memoizer = "0.5.1"
sha2 = "0.10"
itertools = "0.10.3"
mime_guess = "2"
semver = "1.0.7"
actix-web = "4.1.0"
actix-files = "0.6.0"

[dev-dependencies]
fbt-lib = "0.1.18"
indoc = "1"
pretty_assertions = "1"
rusty-hook = "^0.11.2"

[build-dependencies]
vergen = "6"
anyhow = "1.0.53"
