[package]
name = "fpm"
version = "0.1.11"
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
    "Arpita Jaiswal <arpita@fifthtry.com>",
    "Shobhit Sharma <shobhit@fifthtry.com>",
    "Abrar Khan <abrark@fifthtry.com>",
]
edition = "2018"
description = "fpm: FTD Package Manager"
license = "MIT"
repository = "https://github.com/FifthTry/fpm"
homepage = "https://fpm.dev"
build = "build.rs"

[features]
controller = []
remote = []
local = []


[dependencies]
edit = "0.1"
async-recursion = "1"
camino = "1"
clap = "3"
diffy = "0.2"
ftd = { git = "https://github.com/FifthTry/ftd", rev = "7309549" }
#ftd = { path = "../ftd" }
futures = "0.3"
ignore = "0.4"
indoc = "1"
regex = "1"
#reqwest = { version = "0.11.10", features = ["blocking"] }
reqwest = { version = "0.9", features = ["default-tls-vendored"] }
rusqlite = { version = "0.28", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
url = "2"
zip = "0.6"
colorize = "0.1"
chrono = "0.4"
fluent = "0.16"
lazy_static = "1"
realm-lang = "0.1"
antidote = "1"
intl-memoizer = "0.5"
sha2 = "0.10"
itertools = "0.10"
mime_guess = "2"
semver = "1"
actix-web = "4"
actix-files = "0.6"

[dev-dependencies]
fbt-lib = "0.1.18"
indoc = "1"
pretty_assertions = "1"
#rusty-hook = "^0.11.2"

[build-dependencies]
vergen = "7"
anyhow = "1"
