name: Rust Checks

on:
  push:
    branches: [ workflow-debug ]
    paths:
     - '**.rs'
     - 'ftd/**.ftd'
     - 'Cargo.*'
     - 'rust-toolchain'
     - '.github/workflows/rust.yml'
     - 'fastn-core/tests/**'
  pull_request:
    branches: [ workflow-debug ]
    paths:
     - '**.rs'
     - 'ftd/**.ftd'
     - 'Cargo.*'
     - 'rust-toolchain'
     - '.github/workflows/rust.yml'
     - 'fastn-core/tests/**'
jobs:
  everything:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          components: rustfmt, clippy
      - uses: actions/cache@v2  # there is also https://github.com/Swatinem/rust-cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ftd/target
            fifthtry_content/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Show base folder
        id: base-check
        continue-on-error: false
        run: |
          ls -al
      - name: Debug 1
        id: path-check
        continue-on-error: true
        run: |
          ls /home/runner/work/fastn/fastn/fastn-core/
      - name: Debug 2
        id: path-check-2
        continue-on-error: true
        run: |
          ls /home/runner/work/fastn/fastn/fastn-core/..
      - name: Debug 3
        id: path-check-3
        continue-on-error: true
        run: |
          ls -al /home/runner/work/fastn/fastn/fastn-core/../target